#
#Fri Jun 12 23:56:43 ART 2026
artwork_generation_method=ai_generated
bulk=210
destinationFolderPath=carpeta
face_type=real
fake_detailed_type=pencil b&w caricature
fake_group=artwork
fake_type=caricature
format=jpg
identified_face=true
image_recopilation_method=web_crawling
image_recopilation_tool=java_crawler_mp
imagesAmount=10
licence=ol
operatorId=MP
peopleFilePath=people.json
resolution=2mp
type=face
